### PR TITLE
It's aliiiiiive!

### PR DESCRIPTION
**Pull request by dmarcantonio**
image
_it's aliiiiiiiiiive_

Expanded this out to encompass adding the initial behaviour tree. Did some refactoring and made some changes as need. Once @DevYves rocks out the food behaviour, we'll have a snek.

PS: this is Sam
I'm in your base, killing your dudes, Dave 😂

### CODE REVIEW

**Comment by samueljohnwilson** [comment]
Gonna jump in here 👍

**Comment by samueljohnwilson** [comment]
Also, did some cleanup to make sure our naming conventions were consistent across files

**Review by mike-anderson — APPROVED** [review]
manually verified on battlesnake arena - everything currently implemented works wonderfully
alone snake chases its tail until starvation - there does seem to be an off by one bug where it will collide with a snake its own size.

toggling settings, fear is appropriately instilled and self-destruction is immediate

Test suite currently shows no tests running on the following snake brain paths:
`this.action = headbutt;`
`this.action = goingInCircles;`
`this.action = ridingCoattails;`

I don't see a reason to stop this from going forward though - if you'd like @samueljohnwilson I'd be happy to write some tests up for it to bring code cov back up >90%

**Comment by samueljohnwilson** [comment]
> manually verified on battlesnake arena - everything currently implemented works wonderfully
> alone snake chases its tail until starvation - there does seem to be an off by one bug where it will collide with a snake its own size.
> 
> toggling settings, fear is appropriately instilled and self-destruction is immediate
> 
> Test suite currently shows no tests running on the following snake brain paths:
> `this.action = headbutt;`
> `this.action = goingInCircles;`
> `this.action = ridingCoattails;`
> 
> I don't see a reason to stop this from going forward though - if you'd like @samueljohnwilson I'd be happy to write some tests up for it to bring code cov back up >90%

Yeah, that would be great, thanks @mike-anderson 😁

I'm going to take a pause for dinner, but will be plunking away again tonight 👍

**Review by DevYves — APPROVED** [review]

**Pull request merged**
