### PR TITLE
Adds GitHub Action to run unit tests

### PR DESCRIPTION
**Pull request by brandonb927**

### CODE REVIEW

**Review by dmarcantonio — APPROVED** [review]
I guess you have to fix those linting errors 😆

**Comment by brandonb927** [comment]
> I guess you have to fix those linting errors 😆

I'm not super familiar with the types used in `helpers.ts`, or I would

**Comment by samueljohnwilson** [comment]
Looks like the functions just need the return types added

**Comment by brandonb927** [comment]
> Looks like the functions just need the return types added

heh I know this but I don't know what the return types for each function are :)

**Comment by brandonb927** [comment]
Ok I spent like 5 minutes actually reading the `helpers.ts` file and it turned out writing the return functions was pretty simple. Does someone want to ensure I actually set the correct return types?

**Review by samueljohnwilson — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
